export const pricingTiers = {
  monthly: [
    {
      name: "Starter",
      price: "$49",
      annualPrice: "$39",
      schemaPrice: "49",
      description: "For solo operators and small teams ready to replace spreadsheets with real software",
      tagline: "For solo operators and small teams",
      seatInfo: "2 users included · $19/mo per additional user",
      savings: "Save $120/year with annual billing",
      features: [
        "2 users included, $19/mo per additional user",
        "Scheduling, dispatch, CRM, invoicing, and payments",
        "Chemical tracking, customer portal, and recurring automation",
        "Your brand on every invoice, portal, and report",
        "Basic reports and standard support",
      ],
      highlighted: true,
      badge: "Most Popular",
    },
    {
      name: "Professional",
      price: "$99",
      annualPrice: "$89",
      schemaPrice: "99",
      description: "For growing teams that need SMS, QuickBooks, and full visibility into every route",
      tagline: "For growing teams that need more visibility",
      seatInfo: "5 users included · $19/mo per additional user",
      savings: "Save $120/year with annual billing",
      features: [
        "Everything in Starter",
        "5 users included, $19/mo per additional user",
        "SMS reminders with 500 segments included; $0.04/segment overage",
        "License tracking and QuickBooks sync",
        "Technician scorecards, callback tracking, and advanced reporting",
        "Advanced routing and priority support",
      ],
      highlighted: false,
      badge: "Best Value",
    },
  ],
  annual: [
    {
      name: "Starter",
      price: "$39",
      monthlyPrice: "$49",
      schemaPrice: "39",
      description: "For solo operators and small teams ready to replace spreadsheets with real software",
      tagline: "For solo operators and small teams",
      seatInfo: "2 users included · $19/mo per additional user",
      savings: "Save $120/year with annual billing",
      features: [
        "2 users included, $19/mo per additional user",
        "Scheduling, dispatch, CRM, invoicing, and payments",
        "Chemical tracking, customer portal, and recurring automation",
        "Your brand on every invoice, portal, and report",
        "Basic reports and standard support",
      ],
      highlighted: true,
      badge: "Most Popular",
    },
    {
      name: "Professional",
      price: "$89",
      monthlyPrice: "$99",
      schemaPrice: "89",
      description: "For growing teams that need SMS, QuickBooks, and full visibility into every route",
      tagline: "For growing teams that need more visibility",
      seatInfo: "5 users included · $19/mo per additional user",
      savings: "Save $120/year with annual billing",
      features: [
        "Everything in Starter",
        "5 users included, $19/mo per additional user",
        "SMS reminders with 500 segments included; $0.04/segment overage",
        "License tracking and QuickBooks sync",
        "Technician scorecards, callback tracking, and advanced reporting",
        "Advanced routing and priority support",
      ],
      highlighted: false,
      badge: "Best Value",
    },
  ],
} as const;

export const featureRows = [
  { feature: "Users included", starter: "2 included, +$19/mo per additional user", professional: "5 included, +$19/mo per additional user" },
  { feature: "Scheduling", starter: "Included", professional: "Included" },
  { feature: "Dispatch", starter: "Included", professional: "Included" },
  { feature: "Customers / CRM", starter: "Included", professional: "Included" },
  { feature: "Invoicing", starter: "Included", professional: "Included" },
  { feature: "Payments", starter: "Included", professional: "Included" },
  { feature: "Chemical tracking", starter: "Included", professional: "Included" },
  { feature: "Customer portal", starter: "Included", professional: "Included" },
  { feature: "Recurring automation", starter: "Included", professional: "Included" },
  { feature: "Branding: logo + colors", starter: "Included", professional: "Included" },
  { feature: "Reports", starter: "Basic reports", professional: "Advanced reporting" },
  { feature: "SMS reminders", starter: "—", professional: "500 segments included, then $0.04/segment" },
  { feature: "License tracking", starter: "—", professional: "Included" },
  { feature: "QuickBooks sync", starter: "—", professional: "Included" },
  { feature: "Technician scorecards", starter: "—", professional: "Included" },
  { feature: "Callback tracking", starter: "—", professional: "Included" },
  { feature: "Advanced routing", starter: "—", professional: "Included" },
  { feature: "Support", starter: "Standard", professional: "Priority" },
] as const;
