export const pricingTiers = {
  monthly: [
    {
      name: "Starter",
      price: "$99",
      schemaPrice: "99",
      description: "For solo operators ready to replace paper, spreadsheets, and callback chaos.",
      tagline: "For the solo operator ready to go digital",
      features: [
        "Up to 3 users",
        "Scheduling, calendar, and recurring cycles",
        "Customer CRM, service history, and invoicing",
        "Essential chemical application logs",
      ],
      highlighted: false,
      badge: undefined,
    },
    {
      name: "Professional",
      price: "$199",
      schemaPrice: "199",
      description: "For growing teams that need dispatch, automation, and full compliance visibility.",
      tagline: "For growing teams that need more leverage",
      features: [
        "Up to 10 users",
        "Technician accounts and job assignment",
        "Recurring job auto-generation",
        "Full chemical inventory + one-click EPA reports",
      ],
      highlighted: true,
      badge: "Most Popular",
    },
    {
      name: "Enterprise",
      price: "$299",
      schemaPrice: "299",
      description: "For established operators managing multiple crews, territories, or locations.",
      tagline: "For established companies with scale needs",
      features: [
        "Unlimited users",
        "Advanced reporting and technician scorecards",
        "Callback tracking and QA workflows",
        "Custom exports, onboarding, and multi-location support",
      ],
      highlighted: false,
      badge: undefined,
    },
  ],
  annual: [
    {
      name: "Starter",
      price: "$79",
      schemaPrice: "79",
      description: "For solo operators ready to replace paper, spreadsheets, and callback chaos.",
      tagline: "For the solo operator ready to go digital",
      features: [
        "Up to 3 users",
        "Scheduling, calendar, and recurring cycles",
        "Customer CRM, service history, and invoicing",
        "Essential chemical application logs",
      ],
      highlighted: false,
      badge: undefined,
    },
    {
      name: "Professional",
      price: "$169",
      schemaPrice: "169",
      description: "For growing teams that need dispatch, automation, and full compliance visibility.",
      tagline: "For growing teams that need more leverage",
      features: [
        "Up to 10 users",
        "Technician accounts and job assignment",
        "Recurring job auto-generation",
        "Full chemical inventory + one-click EPA reports",
      ],
      highlighted: true,
      badge: "Most Popular",
    },
    {
      name: "Enterprise",
      price: "$249",
      schemaPrice: "249",
      description: "For established operators managing multiple crews, territories, or locations.",
      tagline: "For established companies with scale needs",
      features: [
        "Unlimited users",
        "Advanced reporting and technician scorecards",
        "Callback tracking and QA workflows",
        "Custom exports, onboarding, and multi-location support",
      ],
      highlighted: false,
      badge: undefined,
    },
  ],
} as const;

export const featureRows = [
  {
    feature: "Users included",
    starter: "Up to 3 users",
    professional: "Up to 10 users",
    enterprise: "Unlimited users",
  },
  {
    feature: "Scheduling, calendar, and CRM",
    starter: "Included",
    professional: "Included",
    enterprise: "Included",
  },
  {
    feature: "Recurring cycle management",
    starter: "Included",
    professional: "Auto-generate jobs",
    enterprise: "Auto-generate jobs + custom workflows",
  },
  {
    feature: "Dispatch and routing",
    starter: "Basic route view",
    professional: "Advanced dispatch",
    enterprise: "Advanced + multi-location",
  },
  {
    feature: "Invoicing and payments",
    starter: "Included",
    professional: "Included",
    enterprise: "Included + custom exports",
  },
  {
    feature: "Chemical tracking",
    starter: "Essential application logs",
    professional: "Full inventory + reporting",
    enterprise: "Full inventory + custom exports",
  },
  {
    feature: "EPA compliance reports",
    starter: "Basic manual export",
    professional: "One-click reports",
    enterprise: "One-click + custom exports",
  },
  {
    feature: "Customer reminders",
    starter: "Email",
    professional: "Email + SMS",
    enterprise: "Email + SMS + custom workflows",
  },
  {
    feature: "Reporting dashboards",
    starter: "Core metrics",
    professional: "Operational dashboards",
    enterprise: "Advanced dashboards + scorecards",
  },
  {
    feature: "Callback tracking / QA",
    starter: "—",
    professional: "—",
    enterprise: "Included",
  },
  {
    feature: "Support",
    starter: "Standard",
    professional: "Priority",
    enterprise: "White-glove onboarding",
  },
] as const;
