export const pricingTiers = {
  monthly: [
    {
      name: "Starter",
      price: "$49",
      regularPrice: "$99",
      schemaPrice: "49",
      description: "Early-access founding rate for solo operators ready to replace paper, spreadsheets, and callback chaos.",
      tagline: "For the solo operator ready to go digital",
      features: [
        "1 user",
        "Scheduling, calendar, and recurring cycles",
        "Customer CRM, service history, and invoicing",
        "Essential chemical application logs",
      ],
      highlighted: false,
      badge: "Founding Rate",
    },
    {
      name: "Professional",
      price: "$199",
      schemaPrice: "199",
      description: "For growing teams that need dispatch, automation, and full compliance visibility.",
      tagline: "For growing teams that need more leverage",
      features: [
        "Up to 5 users",
        "Technician accounts and job assignment",
        "Recurring job auto-generation",
        "Full chemical inventory + one-click EPA reports",
      ],
      highlighted: true,
      badge: "Most Popular",
    },
    {
      name: "Enterprise",
      price: "$299",
      schemaPrice: "299",
      description: "For established operators managing multiple crews, territories, or locations.",
      tagline: "For established companies with scale needs",
      features: [
        "Up to 10 users",
        "Advanced reporting and technician scorecards",
        "Callback tracking and QA workflows",
        "Custom exports, onboarding, and multi-location support",
      ],
      highlighted: false,
      badge: undefined,
    },
  ],
  annual: [
    {
      name: "Starter",
      price: "$49",
      regularPrice: "$99",
      schemaPrice: "49",
      description: "Early-access founding rate for solo operators ready to replace paper, spreadsheets, and callback chaos.",
      tagline: "For the solo operator ready to go digital",
      features: [
        "1 user",
        "Scheduling, calendar, and recurring cycles",
        "Customer CRM, service history, and invoicing",
        "Essential chemical application logs",
      ],
      highlighted: false,
      badge: "Founding Rate",
    },
    {
      name: "Professional",
      price: "$169",
      schemaPrice: "169",
      description: "For growing teams that need dispatch, automation, and full compliance visibility.",
      tagline: "For growing teams that need more leverage",
      features: [
        "Up to 5 users",
        "Technician accounts and job assignment",
        "Recurring job auto-generation",
        "Full chemical inventory + one-click EPA reports",
      ],
      highlighted: true,
      badge: "Most Popular",
    },
    {
      name: "Enterprise",
      price: "$249",
      schemaPrice: "249",
      description: "For established operators managing multiple crews, territories, or locations.",
      tagline: "For established companies with scale needs",
      features: [
        "Up to 10 users",
        "Advanced reporting and technician scorecards",
        "Callback tracking and QA workflows",
        "Custom exports, onboarding, and multi-location support",
      ],
      highlighted: false,
      badge: undefined,
    },
  ],
} as const;

export const featureRows = [
  {
    feature: "Users included",
    starter: "1 user",
    professional: "Up to 5 users",
    enterprise: "Up to 10 users",
  },
  {
    feature: "Scheduling",
    starter: "Included",
    professional: "Included",
    enterprise: "Included",
  },
  {
    feature: "Dispatch",
    starter: "Included",
    professional: "Included",
    enterprise: "Included",
  },
  {
    feature: "Customers / CRM",
    starter: "Included",
    professional: "Included",
    enterprise: "Included",
  },
  {
    feature: "Invoicing",
    starter: "Included",
    professional: "Included",
    enterprise: "Included",
  },
  {
    feature: "Customer portal",
    starter: "Included",
    professional: "Included",
    enterprise: "Included",
  },
  {
    feature: "Receivables tracking",
    starter: "Included",
    professional: "Included",
    enterprise: "Included",
  },
  {
    feature: "Team members",
    starter: "—",
    professional: "Up to 5 users",
    enterprise: "Up to 10 users",
  },
  {
    feature: "Chemical tracking",
    starter: "—",
    professional: "Included",
    enterprise: "Included",
  },
  {
    feature: "License tracking",
    starter: "—",
    professional: "Included",
    enterprise: "Included",
  },
  {
    feature: "Recurring automation",
    starter: "—",
    professional: "Included",
    enterprise: "Included",
  },
  {
    feature: "SMS reminders",
    starter: "—",
    professional: "Included",
    enterprise: "Included",
  },
  {
    feature: "Advanced reporting",
    starter: "—",
    professional: "—",
    enterprise: "Included",
  },
  {
    feature: "Technician scorecards",
    starter: "—",
    professional: "—",
    enterprise: "Included",
  },
  {
    feature: "Callback tracking",
    starter: "—",
    professional: "—",
    enterprise: "Included",
  },
  {
    feature: "Custom branding",
    starter: "—",
    professional: "—",
    enterprise: "Included",
  },
  {
    feature: "QuickBooks sync",
    starter: "—",
    professional: "—",
    enterprise: "Included",
  },
  {
    feature: "Support",
    starter: "Standard",
    professional: "Priority",
    enterprise: "White-glove onboarding",
  },
] as const;
